base_url = "https://hayatro.id"
author = "hayatroid"

compile_sass = true
build_search_index = false
minify_html = true

[extra]
author_ja = "ã¯ã‚„ã¨ã‚ã„ã©"
author_bio = "ã‚³ãƒ³ãƒ”ãƒ¥ãƒ¼ã‚¿ã‚’ä½¿ã£ãŸå‰µä½œæ´»å‹•å…¨èˆ¬ã«èˆˆå‘³ã‚ã‚Šã¾ã™ã€‚æ™®æ®µã¯ç«¶æŠ€ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã‚’ã—ã¦ã„ã¾ã™ã€‚"
author_emoji = "ğŸ§‘â€ğŸ’»"
author_twitter = "hayatroid"

[markdown]
highlight_code = true
highlight_theme = "nord"
